MODULES=(ufs-spacemit spacemit-ccu-k3 reset-spacemit-k3 dwmac-spacemit stmmac-platform realtek)
BINARIES=()
FILES=()
HOOKS=(base udev modconf netconf tinyssh block filesystems omarchy-k3-subroot)
COMPRESSION="zstd"
